#!/usr/bin/env node

import fs from "fs";
import path from "path";
import { findArchDir, C } from "../lib/shared.mjs";
import { commandBanner } from "../lib/banner.mjs";
import * as log from "../lib/logger.mjs";
import { loadFile, parseSystem } from "../lib/parsers.mjs";

function banner() {
  commandBanner("arch-export", "Export .arch/ context for different AI tools");
}

// ── Exporters ───────────────────────────────────────────────────────

function exportCursor(archDir, system) {
  log.agent("Generating .cursorrules...");

  let rules = `# Generated by archkit — do not edit manually\n\n`;
  rules += `## Architecture: ${system.pattern}\n\n`;
  rules += `## Rules\n`;
  system.rules.forEach(r => rules += `- ${r}\n`);
  rules += `\n## Reserved Words\n`;
  for (const [k, v] of Object.entries(system.reservedWords)) rules += `- ${k} = ${v}\n`;
  rules += `\n## Naming\nFiles: kebab-case | Types: PascalCase | Funcs: camelCase | Tables: snake_case | Env: SCREAMING_SNAKE\n`;

  // Add boundaries if they exist
  const boundaries = loadFile(archDir, "BOUNDARIES.md");
  if (boundaries) {
    rules += `\n${boundaries}`;
  }

  // Add compact context
  const compact = loadFile(archDir, "CONTEXT.compact.md");
  if (compact) {
    rules += `\n## Quick Reference\n${compact}\n`;
  }

  fs.writeFileSync(".cursorrules", rules);
  log.ok(`.cursorrules (${rules.length} bytes)`);
  return { file: ".cursorrules", size: rules.length };
}

function exportWindsurf(archDir, system) {
  log.agent("Generating .windsurfrules...");

  let rules = `# Generated by archkit\n\n`;
  rules += `## Architecture: ${system.pattern}\n\n`;
  rules += `## Rules\n`;
  system.rules.forEach(r => rules += `- ${r}\n`);
  rules += `\n## Reserved Words\n`;
  for (const [k, v] of Object.entries(system.reservedWords)) rules += `- ${k} = ${v}\n`;
  rules += `\n## Naming Conventions\n`;
  rules += `Files: kebab-case | Types: PascalCase | Funcs: camelCase | Tables: snake_case\n`;

  const boundaries = loadFile(archDir, "BOUNDARIES.md");
  if (boundaries) rules += `\n${boundaries}`;

  fs.writeFileSync(".windsurfrules", rules);
  log.ok(`.windsurfrules (${rules.length} bytes)`);
  return { file: ".windsurfrules", size: rules.length };
}

function exportCopilot(archDir, system) {
  log.agent("Generating .github/copilot-instructions.md...");

  fs.mkdirSync(".github", { recursive: true });

  let instructions = `# Copilot Instructions\n`;
  instructions += `> Generated by archkit\n\n`;
  instructions += `## Architecture\n${system.pattern}\n\n`;
  instructions += `## Rules\n`;
  system.rules.forEach(r => instructions += `- ${r}\n`);
  instructions += `\n## Reserved Words\n`;
  for (const [k, v] of Object.entries(system.reservedWords)) instructions += `- ${k}: ${v}\n`;
  instructions += `\n## Naming\nFiles: kebab-case | Types: PascalCase | Funcs: camelCase | Tables: snake_case | Env: SCREAMING_SNAKE\n`;

  const boundaries = loadFile(archDir, "BOUNDARIES.md");
  if (boundaries) instructions += `\n${boundaries}`;

  fs.writeFileSync(".github/copilot-instructions.md", instructions);
  log.ok(`.github/copilot-instructions.md (${instructions.length} bytes)`);
  return { file: ".github/copilot-instructions.md", size: instructions.length };
}

function exportAider(archDir, system) {
  log.agent("Generating .aider.conf.yml conventions...");

  let conventions = `# Generated by archkit\n`;
  conventions += `# Add to .aider.conf.yml: read: .aider-conventions.md\n\n`;
  conventions += `## Architecture: ${system.pattern}\n\n`;
  conventions += `## Rules\n`;
  system.rules.forEach(r => conventions += `- ${r}\n`);
  conventions += `\n## Reserved Words\n`;
  for (const [k, v] of Object.entries(system.reservedWords)) conventions += `- ${k} = ${v}\n`;

  const boundaries = loadFile(archDir, "BOUNDARIES.md");
  if (boundaries) conventions += `\n${boundaries}`;

  fs.writeFileSync(".aider-conventions.md", conventions);
  log.ok(`.aider-conventions.md (${conventions.length} bytes)`);
  return { file: ".aider-conventions.md", size: conventions.length };
}

function exportAll(archDir, system) {
  const results = [];
  results.push(exportCursor(archDir, system));
  results.push(exportWindsurf(archDir, system));
  results.push(exportCopilot(archDir, system));
  results.push(exportAider(archDir, system));
  return results;
}

// ── Main ────────────────────────────────────────────────────────────

function main() {
  const args = process.argv.slice(2);
  const target = args.find(a => !a.startsWith("-"));
  const jsonMode = args.includes("--json");

  const archDir = findArchDir({ requireFile: "SYSTEM.md" });
  if (!archDir) {
    if (jsonMode) console.log(JSON.stringify({ error: "No .arch/ directory found. Run archkit first." }));
    else { banner(); log.error("No .arch/ directory found. Run archkit or archkit init first."); }
    process.exit(1);
  }

  const systemContent = loadFile(archDir, "SYSTEM.md");
  if (!systemContent) {
    if (jsonMode) console.log(JSON.stringify({ error: "SYSTEM.md not found in .arch/" }));
    else log.error("SYSTEM.md not found.");
    process.exit(1);
  }

  const system = parseSystem(systemContent);

  if (!jsonMode) banner();

  const exporters = {
    cursor: exportCursor,
    windsurf: exportWindsurf,
    copilot: exportCopilot,
    aider: exportAider,
    all: exportAll,
  };

  if (!target || !exporters[target]) {
    if (jsonMode) {
      console.log(JSON.stringify({ error: `Usage: archkit export <${Object.keys(exporters).join("|")}>`, available: Object.keys(exporters) }));
    } else {
      console.error(`  Usage: archkit export <target>\n`);
      console.error(`  Targets:`);
      console.error(`    cursor      Generate .cursorrules`);
      console.error(`    windsurf    Generate .windsurfrules`);
      console.error(`    copilot     Generate .github/copilot-instructions.md`);
      console.error(`    aider       Generate .aider-conventions.md`);
      console.error(`    all         Generate all of the above`);
      console.error("");
    }
    process.exit(1);
  }

  const results = exporters[target](archDir, system);

  if (jsonMode) {
    console.log(JSON.stringify({ success: true, exported: Array.isArray(results) ? results : [results] }));
  }
}

export { main };

if (import.meta.url === `file://${process.argv[1]}` || process.env.ARCHKIT_RUN) {
  main();
}
